services:
  php:
    build: .
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - ./prestashop:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  mariadb:
    image: mariadb:11.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mariadb_data_shine_picking_dashboard_prestashop:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8081:80"

volumes:
  mariadb_data_shine_picking_dashboard_prestashop:

networks:
  default:
    driver: bridge
